### ISSUE TITLE
Bug in docker-in-docker in floki 0.6.0

### ISSUE THREAD

**Issue by maxdymond** [Metaswitch/floki#108]
unknown flag: --link alongguid:floki-docker
See 'docker run --help'.
07:04:50 [ERROR] A problem occured: Running container failed: docker run exited with return code 125

**Comment by maxdymond** [comment]
Fix suggested by @matt-williams is 
https://github.com/Metaswitch/floki/blob/master/src/command.rs#L195:
```
        .add_docker_switch("--link")
        .add_docker_switch(&format!("{}:floki-docker", dind.name()))
```

**Comment by rlupton20** [comment]
Makes sense. I'm sure I grepped for these when I changed this, but must have missed this.

**Comment by rlupton20** [comment]
I labelled `0.6.0` as a bad release - I'm not sure if we can/should retract it.
