### ISSUE TITLE
`floki` doesn't find `Dockerfile` when searching down directories

### ISSUE THREAD

**Issue by rlupton20** [Metaswitch/floki#55]
If your directory tree looks like

```
| floki.yaml
| Dockerfile
| some_folder/
```
and you run `floki` in `some_folder`, then `floki` will search down the directory tree for `floki.yaml`, but if configured to use the `Dockerfile` for the image, it will fail to find the `Dockerfile`.

**Comment by rlupton20** [comment]
@tomwatson1024 you might be interested in this, otherwise I can take it on. It should be an easy fix.

**Comment by tomwatson1024** [comment]
I've had a quick look - I'll try and make a (quick) fix sometime today. I've got a slightly tangential question about the "right" way to do this that someone more familiar with Rust might be able to answer.

We use serde to deserialize the `Image` enum, which includes `PathBuf`s (or `String`s representing paths). It would be nice to be able to transform relative paths _during_ deserialization to be either absolute or relative to the floki root. Patching them after the fact seems a bit unpleasant, as we have to a) mutate the structure and b) publically expose the members that require changing, as the `Image` is automatically deserialized as part of the `Config` struct.

What's the most idiomatic way to do this? I've noticed serde allows use of a custom deserializer function via `serialize_with`, but I can't see how to supply "extra" parameters, e.g. the floki root.

**Comment by rlupton20g** [comment]
No rush on this - no need to worry. I thought you might like to do the fix is all.

Usually I just use functions to do that kind of work. The `Deserialize` instance is just concerned with parsing the configuration file, so I don't think we should start to conflate it's purpose. It might take a bit of playing to find a way to express it with good taste (so to speak).

In general I think the way `floki` is structured follows the pattern

read things (cli, config, environment) -> combine and configure things -> run things

It's possible the `Image` enum conflates the first and middle steps a bit - I wouldn't be against breaking them up.

**Comment by tomwatson1024** [comment]
> No rush on this - no need to worry. I thought you might like to do the fix is all.

Yep, it's interesting enough that I wanted to take a look today 😛 

On your second point - that does make sense. Perhaps the `Image` enum should just represent the config as read, then be passed into some free function, also taking the floki root, that then handles building the image. It seems essentially the same as a "member" function on `Image`, but maybe it better represents what we're after?

**Comment by rlupton20g** [comment]
Yeah - have a go and see. In general feel free to move things around to make them clearer. `floki` grew organically from a few lines of Python, so it's expected to rework things. Rust makes that nice anyway.

**Comment by rlupton20** [comment]
@tomwatson1024 - I think we're done here - do you want to raise an issue to improve the testing?

**Comment by tomwatson1024** [comment]
I've raised https://github.com/Metaswitch/floki/issues/58 to cover the testing improvements.

**Comment by rlupton20g** [comment]
Ace - I'll close this for now. Thanks for the fix!

**Comment by rlupton20** [comment]
Fixed in #56
