### ISSUE TITLE
Assumptions that paths can always be utf-8 decoded

### ISSUE THREAD

**Issue by rlupton20** [Metaswitch/floki#60]
In general in Unix any sequence of non-null bytes is a permissible path. In various places in the source (`interpret.rs` contains examples in `configure_volumes` and `get_mount_specification`) floki does a panicking `to_str`, which may lead to crashes on legitimate (if illegible) paths.

We should audit these and either guarantee they can't cause issues, or deal with them properly. A key question here is probably how to pass these down to the underlying `Command` (if I recall correctly, args are specified with `&str`, but there may be additional methods, I haven't looked).

**Comment by rlupton20** [comment]
Remaining here is to deal with e.g. the SSH authentication socket path, and handling of environment variables in general.

**Comment by rlupton20** [comment]
(Along with checking everything in `command.rs` looks sensible.

**Comment by maxdymond** [comment]
Closed by #101
