### ISSUE TITLE
Allow docker build stages to be used as build environment

### ISSUE THREAD

**Issue by rlupton20** [Metaswitch/floki#66]
It's a common pattern to have multi-stage `Dockerfiles`, an intermediate stage of which is a good candidate for an interactive build container.

It would be useful if `floki` allowed users to select an intermediate stage as its image.

**Comment by tofay** [comment]
Done in https://github.com/Metaswitch/floki/pull/45

**Comment by rlupton20** [comment]
Lol, I need to rtfm. I totally forgot about that! Thanks again for doing it!
