### ISSUE TITLE
use releases

### ISSUE THREAD

**Issue by blakehawkins** [Metaswitch/floki#7]
At present, contributors must bump versions, and the Contributing lifecycle needs to be linearized/special treatment

Tag releases to improve this

**Comment by rlupton20** [comment]
I don't entirely follow what changes you intend here. Delete the `VERSION` file I guess, but the Changelog and Cargo.toml still need changing. Is this avoidable?

**Comment by blakehawkins** [comment]
CHANGELOG, Cargo.toml, VERSION are all fine

This issue is about actually distinguishing 0.0.10 (the first commit that changes the VERSION tag to 0.0.10), vs HEAD

I'm just suggesting to tag and push --tags

**Comment by rlupton20** [comment]
I've got all this working (including automatic deploy). Happy to close?

**Comment by blakehawkins** [comment]
Of course
