### ISSUE TITLE
Automate Cargo dependency bumping

### ISSUE THREAD

**Issue by rlupton20** [Metaswitch/floki#70]
Probably there is something we can use off-the-shelf to submit PRs with dependencies bumped.

Why? It would be good to keep everything nice and up-to-date where possible, but this is boring tedious work.

**Comment by bossmc** [comment]
https://dependabot.com/?  They were recently bought by GitHub, so you'll probably soon be able to enable this natively, in the meantime there's a GitHub app that you can enable.

**Comment by bossmc** [comment]
In fact, I've enabled the dependabot app, as we already have it on the Metaswitch group :)

**Comment by rlupton20** [comment]
Awesome, that looks perfect.

Already have a couple of MRs which I'll handle later. Next step, and ideally, we would have a way to automate additions to the changelog alongside it. I'll look into it.

**Comment by rlupton20** [comment]
This seems to be working reasonably, so I'm going to mark this as fixed.
